name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        🐛 Help us fix this! Describe what's broken, how to reproduce it, and what device/browser you're using.

  - type: textarea
    id: description
    attributes:
      label: What's happening?
      description: Describe the bug
      placeholder: "The header overlaps the hero section on mobile devices..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Open site on iPhone
        2. Scroll down
        3. See header overlap
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen instead?
      placeholder: "The header should stay at the top without overlapping content"

  - type: input
    id: device
    attributes:
      label: Device/Browser
      description: Where did you see this bug?
      placeholder: "iPhone 14 Pro / Safari 17"
    validations:
      required: true
