name: Cleanup / Refactor
description: Code cleanup or refactoring task
title: "[Cleanup]: "
labels: ["cleanup"]
body:
  - type: markdown
    attributes:
      value: |
        💡 Remove redundant code, consolidate duplicates, or refactor for better maintainability.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What are we cleaning up and why?
      placeholder: "We have 3 chat components doing the same thing, causing confusion. Consolidate to just ChatWidget."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Specific tasks to complete
      placeholder: |
        - [ ] Delete unnecessary files
        - [ ] Consolidate duplicate components
        - [ ] Update imports
        - [ ] Test that nothing broke
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Check these off as you verify them
      placeholder: |
        - [ ] No duplicate code
        - [ ] All imports updated
        - [ ] No console errors
        - [ ] Site functions correctly
    validations:
      required: true
