name: Feature / Component
description: New component or feature implementation
title: "[Feature]: "
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature / Component
        Use this template for new components or features (Header, Hero, Services, etc.)

  - type: input
    id: component
    attributes:
      label: Component Name
      description: What are you building? (this will be added to the title)
      placeholder: "e.g., Header Component (Mobile-First)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this component do? Why do we need it?
      placeholder: "The header provides site navigation and branding. It should match the Canvas design with mobile hamburger menu and desktop horizontal nav."
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      description: Modify this list for your specific component
      options:
        - label: Build mobile layout (375px)
        - label: Build desktop layout (1024px+)
        - label: Add responsive breakpoints
        - label: Match Canvas design (colors, spacing, typography)
        - label: Implement accessibility (ARIA labels, keyboard nav)
        - label: Test on real devices

  - type: input
    id: design_reference
    attributes:
      label: Design Reference
      description: Link to Canvas screenshot or Figma
      placeholder: "Canvas screenshot - Header section"

  - type: checkboxes
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      options:
        - label: Works perfectly on mobile (375px)
        - label: Scales smoothly to desktop (1920px)
        - label: Matches Canvas design exactly
        - label: Accessible (WCAG AA compliant)
        - label: No console errors
        - label: Passes manual testing

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Critical (must have for launch)
        - Enhancement (nice to have)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Component Area
      description: Which part of the site?
      options:
        - Header
        - Hero
        - Footer
        - Services
        - Homepage
        - Other
      default: 5
