name: Feature / Component
description: New component or feature implementation
title: "[Feature]: "
labels: ["frontend"]
body:
  - type: markdown
    attributes:
      value: |
        💡 Building a new component? Describe what it does, reference the Canvas design, and break it into tasks.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this component do? Why do we need it?
      placeholder: "The header provides navigation and branding. Should match Canvas design with mobile hamburger menu and desktop horizontal nav."
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: Tasks
      description: Specific tasks to complete
      placeholder: |
        - [ ] Build mobile layout (375px)
        - [ ] Build desktop layout (1024px+)
        - [ ] Match Canvas design
        - [ ] Implement accessibility
        - [ ] Test on real devices
    validations:
      required: true

  - type: input
    id: design_reference
    attributes:
      label: Design Reference
      description: Link to Canvas screenshot or design file
      placeholder: "Canvas screenshot - Header section"

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Check these off as you verify them
      placeholder: |
        - [ ] Works on mobile (375px)
        - [ ] Works on desktop (1920px)
        - [ ] Matches Canvas design
        - [ ] Accessible (WCAG AA)
        - [ ] No console errors
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Component Area
      description: Which part of the site?
      options:
        - Header
        - Hero
        - Footer
        - Services
        - Homepage
        - Chat
        - Other
